language: ruby

install:
  - bundle install

script: script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: "HAOBaxxV4RifJb9t3mcLUcMe4Xwvf+1vGq4kK41jup9NVhdsLr0qmEvLJo7s4mMT1CNhkjGHcX8OG6cA2hJpjZPXm0/kIuKuLmQnwVPVgFtlQZRaUHqPSgQL8K6V4EP5i0TRteE6vHp6ZrSt9Pb0p8nsr85cP/pWnpklFH+iM4d40m/agDlmlpbS9dUbcycRnbjGI7U4lihRYWqkZzGoRF9jFk72a4yE+WZdjz0th5Iwzv8f3DpmVFRfh6BqCqEmMazsrUf2v6NEdE0g5i9a7/0misbPpkJwPCPIVt4Fu9GlmYIMptK6sJJCeFGKCSiw7orY3gz5eyZX6aWCV0fZ/TpUbljruXxdqoqxceCBNdy0JDI6A3RudeJKfGekyTmqS0qewzhLWqTxNFKZ4QWs/sIncujN2336+xRcNStHLr6TFcgpf8T0/H3N23d/JeNvLYW3+DuuqeEwdS8z9e9cALfDVH2djqRhvNlfPDbzpGlFCvrYZ3YnVZ3O401nb4QihTnwkaUrG4gTU4/3QmSUFlYwXb84JtXRIRRExKKwkbgG9PAp2sHNUx/qUelnLhat4NFnrew7uGAP+WGAKZsUxdzMG/egEtfFXCTmaMdioJQKLHiXe3vrjrAuaMv38J/J+GLnF+4MpaCKWHQ5YheS9iACdk8YAjArZzuaWKg8bcI="
