# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: undefined reference
email: oleg.b.antonyan@gmail.com
author: Oleg Antonyan
description: ruby and friends programming blog
keywords: programming, software design, software engineering, ruby, python, mobile, web, rails, ruby on rails, programmer, patterns, iot, rust, c, c++
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://undefined-reference.org" # the base hostname & protocol for your site

# Social links
twitter_link: "https://twitter.com/oleg_antonyan"
bitbucket_link: "https://bitbucket.org/antlabs_dev"
stackoverflow_link: "http://stackoverflow.com/users/1837084/oleg-antonyan"
linkedin_link: "https://www.linkedin.com/in/oleg-antonyan-2b715089"
facebook_link: "https://www.facebook.com/100005362953409"
angelist_link: "https://angel.co/oleg-antonyan"

# Build settings
markdown: kramdown

exclude: [vendor]
