# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: undefined reference to blog
email: oleg.b.antonyan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about programming and related stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social links
twitter_username: oleg_antonyan
github_username:  olegantonyan
stackoverflow_username: oleg-antonyan
stackoverflow_link: "http://stackoverflow.com/users/1837084/oleg-antonyan"
linkedin_username: oleg-antonyan
linkedin_link: "https://www.linkedin.com/in/oleg-antonyan-2b715089"

# Build settings
markdown: kramdown

exclude: [vendor]
